# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95f85f0e425dd7768fec4225011aa715"
name = "product-manual"
application_url = "https://connectors-controller-lovely-bulk.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nobu-checkout-extensibility2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://connectors-controller-lovely-bulk.trycloudflare.com/auth/callback",
  "https://connectors-controller-lovely-bulk.trycloudflare.com/auth/shopify/callback",
  "https://connectors-controller-lovely-bulk.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
